[workspace]
authors = ["Juan P. Fonseca-Zamora <69847296+juanfonsecaLS1@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "explore-superblockify"
platforms = ["win-64","linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.4,<3.15"
osmnx = ">=2.1.0,<3"
geopandas = ">=1.1.3,<2"
rasterio = ">=1.5.0,<2"
shapely = ">=2.1.2,<3"
numba = ">=0.65.0,<0.66"
scipy = ">=1.17.1,<2"
tqdm = ">=4.67.3,<5"
contextily = ">=1.7.0,<2"
"ruamel.yaml" = ">=0.19.1,<0.20"
seaborn = ">=0.13.2,<0.14"
psutil = ">=7.2.2,<8"
typing-extensions = ">=4.15.0,<5"
momepy = ">=0.11.0,<0.12"

